name: Build and sign container image

on:
  - push
  - workflow_dispatch

env:
  REGISTRY: ghcr.io
  COSIGN_KEY: ${{ secrets.COSIGN_KEY }}
  COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

jobs:
  checkout:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
  image-build-push:
    uses: thejaxon/workflows/.github/workflows/image-build-push.yaml@main
    secrets: inherit
    with:
      image_name: ubuntu-24-nginx
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.GITHUB_TOKEN }}
      
  continer-image-signing:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up cosign
        uses: sigstore/cosign-installer@v3.7.0
        with:
          cosign-release: 'v2.4.1'

      - name: Sign container image
        run: cosign sign --yes --key env://COSIGN_KEY --upload=true ${{ env.REGISTRY }}/thejaxon/ubuntu-24-nginx

  trivy-scan-image:
    uses: thejaxon/workflows/.github/workflows/trivy-scan.yaml@main
    needs: image-build-push
    with:
      image_name: ubuntu-24-nginx
