name: Build and sign container image

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  COSIGN_VERSION: 2.4.1
  COSIGN_BINAARY_PATH: /usr/local/bin/cosign

jobs:
  build-push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/sigstore/cosign/releases/download/v${{ env.COSIGN_VERSION }}/cosign-linux-amd64 -O ${{ env.COSIGN_BINAARY_PATH }}
          chmod +x ${{ env.COSIGN_BINAARY_PATH }}

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/thejaxon/ubuntu-24-nginx

      - name: Sign container image
        run: |
          echo ${{ secrets.COSIGN_KEY }} > cosign.key
          cosign sign --key cosign.key --upload=true ${{ env.REGISTRY }}/thejaxon/ubuntu-24-nginx
